stages:
  - build
  - docker-build
  - deploy

build:
  stage: build
  image: node:14
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    paths:
      - build/

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - TIMESTAMP=$(date +%Y%m%d%H%M%S)
    - IMAGE_TAG="$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-$TIMESTAMP"
    - LATEST_TAG="$CI_REGISTRY_IMAGE:latest"
    - echo "Building Docker image with tags $IMAGE_TAG and $LATEST_TAG"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -t $LATEST_TAG .
    - docker push $IMAGE_TAG
    - docker push $LATEST_TAG

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - ssh-keyscan -H $AWS_IP_ADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - ssh ec2-user@$AWS_IP_ADDRESS "bash ./prod-start.sh"
    - rm ~/.ssh/id_rsa