stages:
  - build
  - docker-build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-${date +%Y%m%d%H%M%S}

build:
  stage: build
  image: node:14
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    paths:
      - build/

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    # Add your deployment script/commands here
