name: Sync to GitLab

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync to GitLab
        run: |
          git remote add gitlab https://rahulkanade20:glft-xBx-UZpaj7krx_puX2QH@gitlab.com/monitoring-app1/wkping-frontend.git/
          git config --global user.name "rahulkanade20"
          git config --global user.email "krahul.view@gmail.com"
          git push gitlab HEAD:master --force